# Generated by Django 4.0.3 on 2022-08-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('c_length', models.IntegerField()),
                ('c_duration', models.IntegerField()),
                ('fees', models.FloatField(blank=True, null=True)),
                ('funding', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(null=True, upload_to='images/courses/')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('education', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('email', models.EmailField(default='default@ex.co.ke', max_length=254)),
                ('phone', models.CharField(default='+254 700 000 000', max_length=50)),
                ('social_media', models.CharField(default='default', max_length=50)),
                ('address', models.CharField(default='Default, Setting', max_length=100)),
                ('image_url', models.ImageField(null=True, upload_to='images/teachers/')),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
                ('t_courses', models.ManyToManyField(to='educenter.course')),
                ('t_interest', models.ManyToManyField(to='educenter.interest')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.ImageField(null=True, upload_to='images/scholarship/')),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
                ('s_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.school')),
                ('s_requirement', models.ManyToManyField(to='educenter.requirement')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('image_url', models.ImageField(null=True, upload_to='images/research/')),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('notice_date', models.DateField()),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('location', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('image_url', models.ImageField(null=True, upload_to='images/events/')),
                ('e_speaker', models.ManyToManyField(to='educenter.teacher')),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='c_requirement',
            field=models.ManyToManyField(to='educenter.requirement'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educenter.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educenter.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('post_date', models.DateField()),
                ('post_read', models.IntegerField()),
                ('post_share', models.IntegerField()),
                ('post_comments', models.IntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('image_url', models.ImageField(null=True, upload_to='images/blog/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educenter.teacher')),
                ('header_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.about')),
            ],
            options={
                'ordering': ['heading'],
            },
        ),
    ]
