# Generated by Django 4.0.3 on 2022-08-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='model_name',
            field=models.CharField(default='about', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='model_name',
            field=models.CharField(default='blog', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='model_name',
            field=models.CharField(default='course', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='model_name',
            field=models.CharField(default='event', max_length=100),
        ),
        migrations.AddField(
            model_name='funfact',
            name='model_name',
            field=models.CharField(default='funfact', max_length=100),
        ),
        migrations.AddField(
            model_name='interest',
            name='model_name',
            field=models.CharField(default='interest', max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='model_name',
            field=models.CharField(default='notice', max_length=100),
        ),
        migrations.AddField(
            model_name='requirement',
            name='model_name',
            field=models.CharField(default='requirement', max_length=100),
        ),
        migrations.AddField(
            model_name='research',
            name='model_name',
            field=models.CharField(default='research', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='model_name',
            field=models.CharField(default='scholarship', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='model_name',
            field=models.CharField(default='school', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='model_name',
            field=models.CharField(default='teacher', max_length=100),
        ),
    ]
